language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
before_install:
  - gem install bundler
  - nvm install node
  - bundle
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
# deploy:
#   provider: heroku
#   api_key: ENV['heroku_app_id']
#   app: joe-mecha-whether-sweater
#   run: rails db:migrate